/* eslint-disable @typescript-eslint/no-explicit-any */
/*
AUTOGENERATED: do not edit by hand, your changes will be overwritten 
*/

import { keepPreviousData, useMutation, UseMutationResult, useQuery, useQueryClient, UseQueryResult } from '@tanstack/react-query'
function assertVal<T>(val: T): asserts val is NonNullable<T> {
  if (val === undefined || val === null) {
    throw new Error(`Expected 'val' to be defined, but received ${val}`)
  }
}

export function assertVals<T>(arr: (T | null | undefined)[]): asserts arr is NonNullable<T>[] {
  arr.forEach((val, index) => {
    if (val === undefined || val === null) {
      throw new Error(`Expected element at index ${index} to be defined, but received ${val}`)
    }
  })
}

function unreachable(): never {
  throw new Error(`unreachable code reached`)
}

type QueryKey = (string | number | null | undefined)[]

enum ErrorCode {
  PydanticValidationError = 'PydanticValidationError',
  RequestError = 'RequestError',
}

/**
 * The union of all error types that the request could throw.
 *
 * url: /api/orgs2
 *
 */
export type ResponseErrors = ErrorModel | ErrorModel | PydanticValidationError

/**
 * When all else fails this error is thrown
 *
 */
const RequestError = { error: ErrorCode.RequestError, status_code: -1, request_id: null }

export type MatchInfo = { org_id: string }

export type AdvancedBody = { req_id: string; org_data: AdvancedOrgData | BasicOrgData }

export type BasicOrgData = { org_type: 'basic'; prop_1: string; prop_2: number }

export type AdvancedOrgData = { org_type: 'advanced'; prop_1: string; prop_2: number; prop_3: number }

export type Org = { org_id: string; org_name: string; created_at: Date; updated_at: Date }

export type ErrorModel = { error: string; status_code: number; request_id: null | string }

export type PydanticValidationError = { error: ErrorCode.PydanticValidationError; status_code: number; request_id: null | string; errors: PydanticErrorDetails[] }

export type PydanticErrorDetails = { type: string; loc: (number | string)[]; msg: string; input: string; ctx: Record<string, string> | null }

type ArgType = MatchInfo & AdvancedBody

type HookArgs = { org_id: null | string | undefined; req_id: null | string | undefined; org_data: AdvancedOrgData | BasicOrgData | null | undefined }

export function getOrgFromWire(root: any): Org {
  return { org_id: root.org_id, org_name: root.org_name, created_at: new Date(root.created_at * 1000), updated_at: new Date(root.updated_at * 1000) }
}

export function getErrorModelFromWire(root: any): ErrorModel {
  return { error: root.error, status_code: root.status_code, request_id: root.request_id }
}

export function getPydanticValidationErrorFromWire(root: any): PydanticValidationError {
  return {
    error: root.error,
    status_code: root.status_code,
    request_id: root.request_id,
    errors: root.errors.map((v1: PydanticErrorDetails) => {
      return getPydanticErrorDetailsFromWire(v1)
    }),
  }
}

export function getPydanticErrorDetailsFromWire(root: any): PydanticErrorDetails {
  return {
    type: root.type,
    loc: root.loc,
    msg: root.msg,
    input: root.input,
    ctx:
      root.ctx === null
        ? null
        : Object.fromEntries(
            Object.entries(root.ctx as Record<string, string>).map(([k2, v2]) => {
              return [k2, v2]
            }),
          ),
  }
}

export function convertAdvancedBodyToWire(root: any): AdvancedBody {
  return {
    req_id: root.req_id,
    org_data: root.org_data.org_type === 'basic' ? convertBasicOrgDataToWire(root.org_data) : root.org_data.org_type === 'advanced' ? convertAdvancedOrgDataToWire(root.org_data) : unreachable(),
  }
}

export function convertBasicOrgDataToWire(root: any): BasicOrgData {
  return { org_type: root.org_type, prop_1: root.prop_1, prop_2: root.prop_2 }
}

export function convertAdvancedOrgDataToWire(root: any): AdvancedOrgData {
  return { org_type: root.org_type, prop_1: root.prop_1, prop_2: root.prop_2, prop_3: root.prop_3 }
}

/**
 * The main fetch wrapper that handles serialization/deserialization
 *
 * url: /api/orgs2
 *
 * @param {string} req_id
 * @param {AdvancedOrgData | BasicOrgData} org_data
 * @param {string} org_id
 * @returns {Org}
 *
 */
export async function createOrg2(args: ArgType, base_url: string = 'http://127.0.0.1:8081/', timeout: number = 2000, ...rest: any[]): Promise<Org> {
  const { org_id, req_id, org_data } = args

  const url = `${base_url}api/orgs2`
  const postBody = convertAdvancedBodyToWire(args)
  const response = await fetch(url, { method: 'POST', body: JSON.stringify(postBody), headers: { 'content-type': 'application/json' } })

  if (response.status == 200) {
    return getOrgFromWire(await response.json())
  }

  const data = await response.json()

  if (data.error) {
    switch (data.error) {
      case ErrorCode.PydanticValidationError: {
        throw getPydanticValidationErrorFromWire(data)
      }
      default: {
        throw getErrorModelFromWire(data)
      }
    }
  }

  throw RequestError
}

/**
 * A hook that wraps the fetch call using a react-query mutation
 *
 * args are all nullable so this can be chained with the output of a previous hook easily.
 *
 * url: /api/orgs2
 *
 * @param {string} req_id
 * @param {AdvancedOrgData | BasicOrgData} org_data
 * @param {string} org_id
 * @return {Org} return
 *
 */
export function useCreateOrg2Mutation(args: HookArgs, invalidateQueryKey: QueryKey): UseMutationResult<Org, ResponseErrors, void, unknown> {
  const { org_id, req_id, org_data } = args

  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async () => {
      assertVal(org_id)
      assertVal(req_id)
      assertVal(org_data)
      assertVals(invalidateQueryKey)
      return await createOrg2({ org_id, req_id, org_data })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: invalidateQueryKey })
    },
  })
}

/**
 * A hook that wraps the fetch call using react-query.
 *
 * args are all nullable so this can be chained with the output of a previous hook easily.
 *
 * url: /api/orgs2
 *
 * @param {string} req_id
 * @param {AdvancedOrgData | BasicOrgData} org_data
 * @param {string} org_id
 * @returns {Org}
 *
 */
export function useCreateOrg2(args: HookArgs, enabled: boolean = true): UseQueryResult<Org, ResponseErrors> {
  const { org_id, req_id, org_data } = args

  return useQuery({
    queryKey: ['useCreateOrg2', org_id, req_id, org_data],
    staleTime: 5 * 1000,
    queryFn: async () => {
      return await createOrg2({ org_id, req_id, org_data })
    },
    enabled: enabled,
    placeholderData: keepPreviousData,
  })
}
