/* eslint-disable @typescript-eslint/no-explicit-any */
/*
AUTOGENERATED: do not edit by hand, your changes will be overwritten 
*/

function assertVal<T>(val: T): asserts val is NonNullable<T> {
  if (val === undefined || val === null) {
    throw new Error(`Expected 'val' to be defined, but received ${val}`)
  }
}

export function assertVals<T>(arr: (T | null | undefined)[]): asserts arr is NonNullable<T>[] {
  arr.forEach((val, index) => {
    if (val === undefined || val === null) {
      throw new Error(`Expected element at index ${index} to be defined, but received ${val}`)
    }
  })
}

function unreachable(): never {
  throw new Error(`unreachable code reached`)
}

type QueryKey = (string | number | null | undefined)[]

enum ErrorCode {
  PydanticValidationError = 'PydanticValidationError',
  RequestError = 'RequestError',
}

/**
 * The union of all error types that the request could throw.
 *
 * url: /api/ws/test
 *
 */
export type ResponseErrors = ErrorModel | ErrorModel | PydanticValidationError

/**
 * When all else fails this error is thrown
 *
 */
const RequestError = { error: ErrorCode.RequestError, status_code: -1, request_id: null }

export type Empty = Record<string, unknown>

export type ClientWSMsgA = { type: 'test_client_msg_a'; foo: number }

export type ClientWSMsgB = { type: 'test_client_msg_b'; bar: Date }

export type ServerWSMsgA = { type: 'test_msg_a'; foo: number }

export type ServerWSMsgB = { type: 'test_msg_b'; bar: Date }

export type ErrorModel = { error: string; status_code: number; request_id: null | string }

export type PydanticValidationError = { error: ErrorCode.PydanticValidationError; status_code: number; request_id: null | string; errors: PydanticErrorDetails[] }

export type PydanticErrorDetails = { type: string; loc: (number | string)[]; msg: string; input: string; ctx: Record<string, string> | null }

export type ClientWSMsgs = ClientWSMsgA | ClientWSMsgB

export type ServerMsgs = ServerWSMsgA | ServerWSMsgB

export function getServerMsgsFromWire(root: any): ServerMsgs {
  return root.type === 'test_msg_a' ? getServerWSMsgAFromWire(root) : root.type === 'test_msg_b' ? getServerWSMsgBFromWire(root) : unreachable()
}

export function getServerWSMsgAFromWire(root: any): ServerWSMsgA {
  return { type: root.type, foo: root.foo }
}

export function getServerWSMsgBFromWire(root: any): ServerWSMsgB {
  return { type: root.type, bar: new Date(root.bar * 1000) }
}

export function getErrorModelFromWire(root: any): ErrorModel {
  return { error: root.error, status_code: root.status_code, request_id: root.request_id }
}

export function getPydanticValidationErrorFromWire(root: any): PydanticValidationError {
  return {
    error: root.error,
    status_code: root.status_code,
    request_id: root.request_id,
    errors: root.errors.map((v1: PydanticErrorDetails) => {
      return getPydanticErrorDetailsFromWire(v1)
    }),
  }
}

export function getPydanticErrorDetailsFromWire(root: any): PydanticErrorDetails {
  return {
    type: root.type,
    loc: root.loc,
    msg: root.msg,
    input: root.input,
    ctx:
      root.ctx === null
        ? null
        : Object.fromEntries(
            Object.entries(root.ctx as Record<string, string>).map(([k2, v2]) => {
              return [k2, v2]
            }),
          ),
  }
}
