name: Tox
on: [push]
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Setup postgres
        shell: bash
        run: |
          cd sql
          docker build --progress=plain -t postgres .
          docker run -d --name pg -p 5432:5432 postgres

      - name: Setup redis
        shell: bash
        run: |
          cd redis
          docker build --progress=plain -t redis .
          docker run -d --name redis -p 6379:6379 redis

      - name: Setup Packages
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools tox

      - name: Run Tox
        shell: bash
        run: |
          python -m tox

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
