name: Tox
on: [push]
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Packages
        shell: bash
        run: |
          bun install
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools tox

      - name: Launch Containers
        shell: bash
        run: |
          ./containers.sh

      - name: Tox
        shell: bash
        run: |
          python -m tox

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
