name: Tox
on: [push]
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Python install
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools tox

    - name: Run Tox
      shell: bash
      run: |
        python -m tox